### ISSUE TITLE
Add Java sample app.

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/gonut#11]
Add Java-based sample app to the list of sample apps.

**Comment by m-lukas** [comment]
I tried different flavors of the CF Java Buildpack and made following experiences:

### Spring Boot [(Buildpack Link)](github.com/cloudfoundry/java-buildpack/blob/master/docs/container-spring_boot.md):
- requires a compiled .jar file and dependency manager like Gradle or Maven
-> easy to bootstrap the project by using Spring Starter Kit (https://start.spring.io/)
- less complex folder structure possible
- [GitHub Repo](https://github.com/m-lukas/java-springboot-helloworld)
- !!! size of .jar file ~17 MB
- push-time: ~2-3 minutes

=> pre-combiled applications aren't ideal for GoNut because they increase the size of the binary significantely and don't follow the idea of portability

### Liberty/IBM Websphere [(Buildpack Link)](https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/blob/master/docs/container-liberty.md):
- requires a compiled .jar file and dependency manager like Gradle or Maven
- more complicated local development -> Liberty and Websphere Development Tools and Runtime
- very static folder structure
- less documented
- [GitHub Repo](https://github.com/m-lukas/java-liberty-helloworld)

### Groovy [(Buildpack Link)](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-groovy.md):
- does not require a compiled .jar file
- is only a replacement for Jave, SpringBoot as underlying framework is still necessary
- !!! also includes many libaries which are not packed into the .jar-file and have to be pushed as well
-> probably no size difference to a compiled .jar file
- I had issues with the SpringBoot libary for the RestController due to Gradle

### Alternatives [(using Java Main)](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-java_main.md):
Great exemples for minimal Java-Servers:
- [(Link to article)](https://syntaxcorrect.com/Java/5_Ultra_Lightweight_Http_Server_Implementations_in_Java_for_Blazing_Fast_Microservices_APIs_or_Even_Websites)

### Embedded Web Server [(Example)](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/example-embedded-web-server.md):
- not tested yet
